Update mole

diff --git a/mole b/mole
--- a/mole
+++ b/mole
@@ -18,8 +18,13 @@ usage(){
 open_file() {
   file="$1"
   group="$OPTARG"
+
   if [ -z "$file" ]; then
     echo "No file specified."
+    exit 1
+  fi
+  if [ ! -f "$file" ]; then
+    echo "File does not exist."
     exit 1
   fi
   if [ -n "$group" ]; then
@@ -41,9 +46,10 @@ mole() {
   BEFORE=""
   AFTER=""
   most=false
+
   while getopts "g:a:b:m" opt; do
     case $opt in
-      g) group=$OPTARG ;;
+      g) groups=$OPTARG ;;
       a) BEFORE=$OPTARG ;;
       b) AFTER=$OPTARG ;;
       m) most=true ;;
@@ -52,18 +58,22 @@ mole() {
     esac
   done
   shift $((OPTIND-1))
-
+  for g in $(echo "$group" | tr ',' ' '); do
+    groups="$groups $g"
+  done
+  groups=${groups# }
+  
   if expr "$BEFORE" : '^[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}$' > /dev/null; then
-    BEFORE=$(date -d "$BEFORE" +%s)
+    BEFORE=$(date -d "$BEFORE" +%F)
   elif [ -n "$BEFORE" ]; then
-    echo "Invalid date format for -a" >&2
+    echo "Invalid date format for -b" >&2
     exit 1
   fi
 
   if expr "$AFTER" : '^[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}$' > /dev/null; then
-    AFTER=$(date -d "$AFTER" +%s)
+    AFTER=$(date -d "$AFTER" +%F)
   elif [ -n "$AFTER" ]; then
-    echo "Invalid date format for -b" >&2
+    echo "Invalid date format for -a" >&2
     exit 1
   fi
   file=""
@@ -73,30 +83,31 @@ mole() {
   else
     dir="$1"
   fi
-
+   
   if [ -z "$group" ] && [ -z "$BEFORE" ] && [ -z "$AFTER" ]; then
     if [ $most = true ]; then
-      file=$(awk -F ';' '{print $1}' "$MOLE_RC" | grep -E "^$dir/.*" | sort | uniq -c | sort -nr | head -n 1 | awk '{print $2}')
+      file=$(awk -F ';' '{print $1}' "$MOLE_RC" | grep -E "^${dir}/.*" | sort | uniq -c | sort -nr | head -n 1 | awk '{print $2}')
     elif [ $most = false ]; then
-      file=$(awk -F ';' '{print $1}' "$MOLE_RC" | grep -E "^$dir/.*" | tail -n 1 | awk '{print $1}')
+      file=$(awk -F ';' '{print $1}' "$MOLE_RC" | grep -E "^${dir}/.*" | tail -n 1 | awk '{print $1}')
     fi
 
   else    
-    file_list=$(awk -v group="$group" -v BEFORE="$BEFORE" -v AFTER="$AFTER" '
-      BEGIN {
-        FS=";"
-        OFS=";"
-      }
-      {
-        if (group == "" || group == $3) {
-          if (BEFORE == "" || BEFORE >= $2) {
-            if (AFTER == "" || AFTER <= $2) {
-              print $1
-            }
-          }
-        }
-      }' "$MOLE_RC" | grep -E "^$dir/.*" | sort | uniq -c | sort -rn)
 
+    file_list=$(awk -v groups="$groups" -v BEFORE="$BEFORE" -v AFTER="$AFTER" '
+  BEGIN {
+    FS=";"
+    OFS=";"
+  }
+  { 
+    if (groups == "" || groups == $3) {
+      if (BEFORE == "" || BEFORE >= $2) {
+        if (AFTER == "" || AFTER <= $2) {
+          print $1
+        }
+      }
+    }
+    }
+  }' "$MOLE_RC" | grep -E "^${dir}/.*" | sort | uniq -c | sort -rn )
     if [ $most = true ]; then
       file=$(echo "$file_list" | head -n 1 | awk '{ print $2 }')
     elif [ $most = false ]; then
@@ -138,20 +149,23 @@ list_files() {
   fi
 
   if expr "$BEFORE" : '^[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}$' > /dev/null; then
-    BEFORE=$(date -d "$BEFORE" +%s)
+    BEFORE=$(date -d "$BEFORE" +%F)
   elif [ -n "$BEFORE" ]; then
-    echo "Invalid date format for -a" >&2
-    exit 1
-  fi
-
-  if expr "$AFTER" : '^[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}$' > /dev/null; then
-    AFTER=$(date -d "$AFTER" +%s)
-  elif [ -n "$AFTER" ]; then
     echo "Invalid date format for -b" >&2
     exit 1
   fi
 
-  awk -v group="$group" -v BEFORE="$BEFORE" -v AFTER="$AFTER" -v dir="$dir" '
+  if expr "$AFTER" : '^[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}$' > /dev/null; then
+    AFTER=$(date -d "$AFTER" +%F)
+  elif [ -n "$AFTER" ]; then
+    echo "Invalid date format for -a" >&2
+    exit 1
+  fi
+  virgin_rc=$(cat "$MOLE_RC") 
+  sorted_rc=$(awk -F';' '{print $3,$2,$1}' "$MOLE_RC" | sort | awk '{print $3";"$2";"$1}')
+  echo "$sorted_rc" | sed 's/^;//' > "$MOLE_RC"
+
+file_list=$( awk -v group="$group" -v BEFORE="$BEFORE" -v AFTER="$AFTER" -v dir="$dir" '
   BEGIN {
     FS=";"
     OFS=";"
@@ -160,18 +174,19 @@ list_files() {
     if (group == "" || group == $3) {
       if (BEFORE == "" || BEFORE >= $2) {
         if (AFTER == "" || AFTER <= $2) {
-          if (files[$1] == "") {
-            files[$1] = $3
-          } else {
-            if ( $3 != ""){
-            files[$1] = files[$1] "," $3}
-          }
-          for (file in files) {
-            cmd = "basename \"" file "\""
-            cmd | getline basename
-            close(cmd)
-            if (indent < length(basename)) {
-              indent = length(basename)+1
+          if (!(files[$1] ~ "(^|,)" $3 "($|,)")) {
+            if (files[$1] == "") {
+              files[$1] = $3
+            } else {
+              files[$1] = files[$1] "," $3
+            }
+            for (file in files) {
+              cmd = "basename \"" file "\""
+              cmd | getline basename
+              close(cmd)
+              if (indent < length(basename)) {
+                indent = length(basename)+1
+              }
             }
           }
         }
@@ -183,13 +198,14 @@ list_files() {
       cmd = "basename \"" file "\""
       cmd | getline basename
       close(cmd)
-
-      printf "%s:%*s%s\n", basename, indent - length(basename) , "", files[file] == "" ? "-" : files[file]
+      printf "%s:%*s%s\n", basename, indent - length(basename) , "", files[file] == "" ? "-" : files[file] 
     }
-  }' "$MOLE_RC" | sort -n
+  }' "$MOLE_RC" )
 
-  echo "$file_list"
+  echo "$virgin_rc" > "$MOLE_RC"
+echo "$file_list"
 }
+
 
 
 secret_log() {
@@ -210,37 +226,45 @@ secret_log() {
       esac
   done
   shift $((OPTIND -1))
-  
-  if expr "$BEFORE" : '^[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}-[0-9]{2}-[0-9]{2}$' > /dev/null; then
-    BEFORE=$(date -d "$BEFORE" +%s)
-  elif [ -n "$BEFORE" ]; then
-    echo "Invalid date format for -a" >&2
-    exit 1
-  fi
 
-  if expr "$AFTER" : '^[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}-[0-9]{2}-[0-9]{2}$' > /dev/null; then
-    AFTER=$(date -d "$AFTER" +%s)
-  elif [ -n "$AFTER" ]; then
+  if expr "$BEFORE" : '^[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}_[0-2]\{1\}[0-9]\{1\}-[0-6]\{1\}[0-9]\{1\}-[0-6]\{1\}[0-9]\{1\}$' > /dev/null; then
+    BEFORE=$(echo "$BEFORE" )
+  elif [ -n "$BEFORE" ]; then
     echo "Invalid date format for -b" >&2
     exit 1
   fi
 
-  FILES=$(grep -E "^$DIR/.*;[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}-[0-9]{2}-[0-9]{2}" "$MOLE_RC" | cut -d';' -f1 | sort -u )
-
-  if [ -n "$BEFORE" ]; then
-    FILES=$(echo "$FILES" | xargs stat -f '%a %N' | awk -v before="$BEFORE" '$1 < strftime("%s", before) {print $2}')
-  fi
-  if [ -n "$AFTER" ]; then
-    FILES=$(echo "$FILES" | xargs stat -f '%a %N' | awk -v after="$AFTER" '$1 > strftime("%s", after) {print $2}')
+  if expr "$AFTER" : '^[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}_[0-2]\{1\}[0-9]\{1\}-[0-6]\{1\}[0-9]\{1\}-[0-6]\{1\}[0-9]\{1\}$' > /dev/null; then
+    AFTER=$(echo "$AFTER" )
+  elif [ -n "$AFTER" ]; then
+    echo "Invalid date format for -a" >&2
+    exit 1
   fi
 
+  # TODO: Filter files by directory
+  virgin_rc=$(cat "$MOLE_RC") 
+  sorted_rc=$(awk -v BEFORE="$BEFORE" -v AFTER="$AFTER" '
+  BEGIN {
+    FS=";"
+    OFS=";"
+  }
+  { 
+    if (BEFORE == "" || BEFORE >= $2) {
+      if (AFTER == "" || AFTER <= $2) {
+        print $1,$2
+      }
+    }
+  }' "$MOLE_RC"  | sort )
+  echo "$sorted_rc" | sed 's/^;//' > "$MOLE_RC"
+  FILES=$(cut -d';' -f1 "$MOLE_RC" | sort -u)
+  
   LOG_FILE="$LOG_DIR/log_$(whoami)_$(date +%Y-%m-%d_%H-%M-%S)"
-  for FILE in $FILES; do
+  printf "%s\n" "$FILES" | while read -r FILE; do
       FILE_PATH="$FILE"
       FILE_OPEN_TIMES=$(grep "^$FILE_PATH;" "$MOLE_RC" | cut -d';' -f2- | cut -d';' -f1 | tr '\n' ';' | sed 's/;$//')
       printf "%s;%s\n" "$FILE_PATH" "$FILE_OPEN_TIMES" >> "$LOG_FILE"
   done
-
+  echo "$virgin_rc" > "$MOLE_RC"
   bzip2 "$LOG_FILE"
 }
 
@@ -257,16 +281,14 @@ elif [ "$1" = "secret-log" ]; then
   secret_log "$@" 
   exit 0
 elif [ -n "$1" ]; then
-  if [ "$1" = "-m" ] || [ -d "$1" ]; then
+  if [ "$1" = "-m" ] || [ -d "$1" ] || [ "$1" = "-g" ] || [ "$1" = "-a" ] || [ "$1" = "-b" ]; then
   mole "$@"
   fi
-  while getopts "g:hab" opt; do
+  while getopts "g:h" opt; do
   case $opt in
     h) usage
       exit 0 ;;
-    g) open_file "$3" "$OPTARG" ;;
-    a) mole "$@" ;;
-    b) mole "$@" ;;
+    g) open_file "$3" "$OPTARG" ;; 
     \?) echo "Invalid option" >&2
         exit 1 ;;
   esac
